### ISSUE TITLE
Error in regex for sic_code

### ISSUE THREAD

**Issue by raoulsullivan** [FundingOptions/sme-finance-application-schema#28]
Deniz at FundingXchange points out:

The current regex pattern for the sic_code is: 
^([a-uA-U]|[0-9]{1,2}|[0-9]{1,2}\\.[0-9]{1,2}|[0-9]{1,2}\\.[0-9]{1,2}/[0-9])$

The highlighted slash ["{1,2}/[0-9])$"] causes an error when this expression is evaluated.

**Comment by raoulsullivan** [comment]
This looks odd to me since it's replaced two double-escape slashes. However, it checks out at regexr.com. @nesaro your opinion please?

**Comment by cybojenix** [comment]
from ECMA-262:
```
RegularExpressionChar ::
    RegularExpressionNonTerminator but not one of \ or / or [
    RegularExpressionBackslashSequence
    RegularExpressionClass
```

essentially, you need to escape `/` when using regex.

Also since these are normal strings (and not the raw strings you are used to using in python), the escape character also needs escaping.
`\\.`, `\\/`. not `\.`, `\/`

**Comment by raoulsullivan** [comment]
Yup. Amended the PR
